
-- STAFF
CREATE TABLE STAFF(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(15) UNIQUE,
    EMAIL VARCHAR(30) UNIQUE,
    SEX VARCHAR(20)
)
-- CUSTOMER
CREATE TABLE CUSTOMER(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(15),
    SEX VARCHAR(20),
    TYPE_CUSTOMER VARCHAR(20),
    TOTAL_POINT VARCHAR(100)
)

-- BILL
CREATE TABLE BILL(
	ID_CUSTOMER VARCHAR(10),
    MOVIE_NAME VARCHAR(50),
    CINEMA_NAME VARCHAR(50),
    TIME_SLOT VARCHAR(20),
    SEATS VARCHAR(100),
    DATE_BOUGHT VARCHAR(30),
    PRICE VARCHAR(30),
    DISCOUNT VARCHAR(30)
)
-- TABLE VIP CUSTOMER
CREATE TABLE VIPCUSTOMER(
	PHONE_NUMBER VARCHAR(15) NOT NULL PRIMARY KEY,
    FULL_NAME VARCHAR(30),
    SEX VARCHAR(10)
)
-- ACCOUNT
CREATE TABLE ACCOUNT(
	USERNAME VARCHAR(30) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(50)
)

